name: Automated Tests CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  automated-tests-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.9
      - name: Test with gradle
        run: gradle clean check