name: Sync Fork

on:
  schedule:
    - cron: '30 14 * * 1' # every Monday at 14:30 UCT 
  workflow_dispatch: # on button click for manual testing

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4 #1.4 is stable but may need to be updated
        with:
          owner: HL7-DaVinci
          base: master # Upstream
          head: master # local
          ignore_fail: true 
          auto_merge: false 
          pr_title: Fork Auto Sync
          pr_message: Upstream repository has been updated - Please review changes 
